# Generated by Django 5.2.11 on 2026-07-14 09:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_src', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('application_id', 'pack')},
        ),
        migrations.CreateModel(
            name='PackGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('packs', models.ManyToManyField(related_name='groups', to='app_src.pack')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='app_src.packgroup'),
        ),
    ]
