# Generated by Django 5.2.11 on 2026-06-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_src', '0002_pack'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
            ],
        ),
    ]
