# Generated by Django 5.2.11 on 2026-06-16 17:52

from django.db import migrations

def seed_questions(apps, schema_editor):
    QuestionTable = apps.get_model("app_src", "QuestionTable")

    QuestionTable.objects.create(question="Random Q1")
    QuestionTable.objects.create(question="Random Q2")
    QuestionTable.objects.create(question="Random Q3")
    QuestionTable.objects.create(question="Random Q4")
    QuestionTable.objects.create(question="Random Q5")
    QuestionTable.objects.create(question="Random Q6")
    QuestionTable.objects.create(question="Random Q7")
    QuestionTable.objects.create(question="Random Q8")
    QuestionTable.objects.create(question="Random Q9")
    QuestionTable.objects.create(question="Random Q10")



class Migration(migrations.Migration):

    dependencies = [
        ('app_src', '0003_questiontable'),
    ]

    operations = [
        migrations.RunPython(seed_questions),
    ]
