# Generated by Django 5.2.11 on 2026-06-17 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_src', '0002_create_account_type_groups'),
        ('app_src', '0004_auto_20260616_1852'),
    ]

    operations = [
    ]
