# Generated by Django 5.2.11 on 2026-06-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_src', '0005_merge_20260617_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='pre_interview_question_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pack',
            name='pre_interview_question_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pack',
            name='pre_interview_question_3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='questiontable',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
