# Generated by Django 5.2.11 on 2026-06-18 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_src', '0005_merge_20260617_1106'),
        ('app_src', '0006_seed_categories'),
    ]

    operations = [
    ]
