# Generated by Django 5.2.11 on 2026-06-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_src', '0006_pack_pre_interview_question_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='pack_class',
            field=models.CharField(choices=[('apprentice', 'Apprentice'), ('staff', 'Staff'), ('manager', 'Manager')], default='apprentice', max_length=20),
        ),
    ]
