# Generated by Django 5.2.11 on 2026-06-22 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_src', '0005_merge_20260617_0932'),
        ('app_src', '0005_merge_20260617_1012'),
        ('app_src', '0008_application'),
    ]

    operations = [
    ]
