# Generated by Django 5.2.11 on 2026-06-22 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_src', '0010_pack_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='pack_class',
        ),
        migrations.AlterField(
            model_name='pack',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='app_src.category'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='pre_interview_question_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pack',
            name='pre_interview_question_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pack',
            name='pre_interview_question_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
