# Generated by Django 5.2.11 on 2026-06-22 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_src', '0008_questiontable_category_alter_note_id_alter_pack_id_and_more'),
        ('app_src', '0009_merge_20260622_1352'),
        ('app_src', '0011_remove_pack_pack_class_alter_pack_category_and_more'),
    ]

    operations = [
    ]
