# Generated by Django 5.2.11 on 2026-06-23 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_src', '0009_merge_20260622_0943'),
        ('app_src', '0012_merge_20260622_1944'),
    ]

    operations = [
    ]
