# Generated by Django 5.2.11 on 2026-06-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_src', '0013_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='packs', to='app_src.questions'),
        ),
    ]
