# Generated by Django 5.2.11 on 2026-06-24 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_src', '0013_application_interview_date_application_status'),
        ('app_src', '0014_interviewresponse'),
    ]

    operations = [
    ]
