# Generated by Django 5.2.11 on 2026-06-24 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_src', '0014_interviewresponse'),
        ('app_src', '0014_pack_questions'),
    ]

    operations = [
    ]
