# Generated by Django 5.2.11 on 2026-06-24 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_src', '0015_merge_20260624_1156'),
        ('app_src', '0015_merge_20260624_1316'),
    ]

    operations = [
    ]
