# Generated by Django 5.2.11 on 2026-06-24 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_src', '0015_merge_0014_interviewresponse_0014_pack_questions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interviewresponse',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='interviewresponse',
            name='updated_at',
        ),
    ]
