# Generated by Django 5.2.11 on 2026-06-25 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_src', '0015_merge_20260624_1156'),
        ('app_src', '0015_merge_20260624_1316'),
        ('app_src', '0016_alter_interviewresponse_question'),
    ]

    operations = [
    ]
