# Generated by Django 5.2.11 on 2026-06-24 13:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_src', '0017_merge_20260624_1413'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='questions',
        ),
        migrations.AddField(
            model_name='interviewresponse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='interviewresponse',
            unique_together={('user', 'question')},
        ),
    ]
