# Generated by Django 5.2.11 on 2026-06-24 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_src', '0018_remove_pack_questions_interviewresponse_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_src.questions'),
        ),
        migrations.DeleteModel(
            name='QuestionTable',
        ),
    ]
