# Generated by Django 5.2.11 on 2026-06-24 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_src', '0016_merge_20260624_1418'),
        ('app_src', '0019_alter_interviewresponse_question_and_more'),
    ]

    operations = [
    ]
