# Generated by Django 5.2.11 on 2026-06-26 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_src', '0020_merge_20260624_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('category', models.CharField(choices=[('Category 1', 'Category 1'), ('Category 2', 'Category 2'), ('Category 3', 'Category 3'), ('Category 4', 'Category 4')], default='Category 1', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='average_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='InterviewResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('feedback', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='app_src.application')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_src.questions')),
            ],
            options={
                'unique_together': {('application', 'question')},
            },
        ),
    ]
