# Generated by Django 5.2.11 on 2026-06-29 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_src', '0018_indicator'),
        ('app_src', '0021_questiontable_application_average_score_and_more'),
    ]

    operations = [
    ]
