# Generated by Django 5.2.11 on 2026-07-06 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_src', '0024_indicator_name_indicatorscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='question',
        ),
    ]
