# Generated by Django 5.2.11 on 2026-07-07 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_src', '0024_indicator_name_indicatorscore'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interviewresponse',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='interviewresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='interviewresponse',
            name='user',
        ),
        migrations.DeleteModel(
            name='QuestionTable',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='name',
        ),
        migrations.DeleteModel(
            name='InterviewResponse',
        ),
    ]
