# Generated by Django 5.2.11 on 2026-07-06 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_src', '0024_indicator_name_indicatorscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='question',
        ),
        migrations.AlterField(
            model_name='indicator',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='app_src.questions'),
        ),
    ]
