# Generated by Django 5.2.11 on 2026-07-06 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_src', '0025_remove_indicator_question_alter_indicator_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='app_src.category'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
