# Generated by Django 5.2.11 on 2026-07-08 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_src', '0030_indicatorgroupscore_notes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interviewresponse',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='interviewresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='interviewresponse',
            name='user',
        ),
        migrations.DeleteModel(
            name='QuestionTable',
        ),
        migrations.DeleteModel(
            name='InterviewResponse',
        ),
    ]
