# Generated by Django 5.2.11 on 2026-07-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_src', '0031_alter_interviewresponse_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pack',
            name='pre_interview_question_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pack',
            name='pre_interview_question_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pack',
            name='pre_interview_question_3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
