# Generated by Django 5.2.11 on 2026-07-14 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_src', '0032_alter_category_description_and_more'),
        ('app_src', '0032_applicationpack'),
    ]

    operations = [
    ]
